name: Andy Cook
description: Software Developer from Readify
avatar: https://avatars3.githubusercontent.com/u/1923924
url: "http://andycook71.github.io/"
title_description: "Various bits and pieces."
title_image: "http://2.gravatar.com/avatar/e223a319bb5a2722b769837e7f278ed7?s=150"
google_analytics: "UA-65721449-1"
disqus_account: andycook71
github_repository: https://github.com/andycook71/andycook71.github.io
addthis_id: 
post_limit: 5
footer-links:
  dribbble:
  email: andycook71@hotmail.com
  facebook: andy.cook.96930
  flickr:
  github: andycook71
  instagram:
  linkedin: andycook71
  pinterest: andycook71
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: andycook71
  stackoverflow: users/820344/andy-cook
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: 


# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: rouge
permalink: /:title/

# The release of Jekyll Now that you're using
version: v3.1.1

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME

    # Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]

